name: allenact
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - black=19.10b0
  - colour=0.1.5
  - coverage=5.3
  - filelock=3.0.12
  - flake8=3.8.4
  - gitpython=3.1.9
  - ipython
  - markdown=3.3
  - matplotlib>=3.3.1
  - mypy=0.790
  - networkx=2.5
  - numpy>=1.19.1
  - pandas>=1.1.3
  - patsy=0.5.1
  - pillow<7.0.0
  - pip
  - pytest>=6.1.1
  - python=3.6.12
  - cudatoolkit=10.2
  - pytorch >=1.6.0,<1.7.0
  - quaternion>=2020.9.5.14.42.2
  - ruamel.yaml
  - scipy=1.5.2
  - setproctitle
  - tensorboard=2.2.1
  - torchvision>=0.7.0
  - tqdm
  - setuptools
  - pip:
    - "--editable=git+https://github.com/allenai/ai2thor.git@ExpRoom#egg=ai2thor"
    - "--editable=git+https://github.com/unnat/babyai.git@ff645fe00ea8412a29bd5e2d6f79ae1595d229a7#egg=babyai"
    - "--editable=git+https://github.com/facebookresearch/habitat-lab.git@03bf97ec232fb2f92620eaae43c569ff84bdf2ce#egg=habitat"
    - numpy-quaternion
    - docformatter==1.3.1
    - docstr-coverage==1.2.0
    - gin-config==0.3.0
    - "gym>=0.17.0,<0.18.0"
    - gym-minigrid==1.0.1
    - mkdocs==1.1.2
    - mkdocs-material==5.5.3
    - moviepy==1.0.3
    - pipenv-setup==3.1.1
    - pre-commit==2.7.1
    - pydoc-markdown==3.4.0
    - pyquaternion==0.9.9
    - tensorboardx==2.1
prefix: /anaconda3/envs/allenact
