channels:
  - defaults
  - conda-forge
dependencies:
  - black=23.3.0
  - docformatter>=1.3.1
  - gitpython
  - markdown>=3.3
  - mkdocs>=1.1.2
  - mkdocs-material>=5.5.3
  - mkdocs-material-extensions>=1.0
  - mypy
  - pre-commit
  - pytest>=6.1.1
  - ruamel.yaml
  - pip:
    - pydoc-markdown>=3.4.0
